In [11]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np

res = requests.get("http://www.baseball-reference.com/players/l/landiji01.shtml")
soup = BeautifulSoup(res.text, "lxml")

data = []
table = soup.find('table', attrs={'class':'stats_table'})
table_body = table.find('tbody')

rows = table_body.find_all('tr')
for row in rows:
    cols = row.find_all('td')
    cols = [ele.text.strip() for ele in cols]
    data.append([ele for ele in cols if ele]) # Get rid of empty values
    
frame = pd.DataFrame(data,index=p_head)

ValueError: Shape of passed values is (29, 21), indices imply (29, 30)

In [2]:
frame.head

<bound method NDFrame.head of                                                    0        1     2     3   \
0                                                  18  CHW-min     D    92
1                                                  19  CHW-min     A   128
2   Did not play in major or minor leagues (Milita...     None  None  None
3   Did not play in major or minor leagues (Milita...     None  None  None
4                                                  22  CHW-min  AA,A   105
5                                                  23  CHW-min   AAA    37
6                                                  23      CHW    AL    96
7                                                  24      CHW    AL   142
8                                                  25      CHW    AL   149
9                                                  26      CHW    AL   148
10                                                 27      CHW    AL   140
11                                                 28      CHW    AL   149
12                                                 29      CHW    AL   133
13                                                 30      CHW    AL   106
14                                                 31      KCA    AL   118
15                                                 32      CLE    AL    85
16                                                 33      TOT   MLB    80
17                                                 33      TOT    AL    30
18                                                 33      HOU    NL    50
19                                                 33      DET    AL    25
20                                                 33      BOS    AL     5

      4     5     6     7     8     9   ...      19    20    21    22    23  \
0    318   318    87     9     4     4  ...    None  None  None  None  None
1    473   473   148    23     4    14  ...    None  None  None  None  None
2   None  None  None  None  None  None  ...    None  None  None  None  None
3   None  None  None  None  None  None  ...    None  None  None  None  None
4    337   337    95    14     4     6  ...    None  None  None  None  None
5    140   118    21    29     1     4  ...      47     3     1     1     0
6    324   274    38    58    11     3  ...    .625    72    81     3     3
7    593   523    72   145    23     7  ...    .785   116   227     9     8
8    623   515    78   140    26     7  ...    .749   108   195     5     8
9    593   494    89   125    25     6  ...    .753   105   192     7     9
10   618   534    87   151    18     8  ...    .832   123   251    10     4
11   629   534    82   122    21     6  ...    .711    92   200    10     9
12   454   396    56    89     6     6  ...    .685    93   146     4     6
13   347   298    30    62     8     4  ...    .577    65    81     5     6
14   431   364    46    87    15     1  ...    .656    89   113    10     3
15   180   158    23    35     5     1  ...    .639    85    51     2     2
16   231   198    24    47    11     1  ...    .693   102    72     0     1
17    64    55     5    11     0     0  ...    .661    92    20     0     0
18   167   143    19    36    11     1  ...    .705   106    52     0     1
19    56    48     4    10     0     0  ...    .637    86    16     0     0
20     8     7     1     1     0     0  ...    .821   128     4     0     0

          24    25    26    27     28
0       None  None  None  None   None
1       None  None  None  None   None
2       None  None  None  None   None
3       None  None  None  None   None
4       None  None  None  None   None
5   INA · AA  None  None  None   None
6          2     0     2   987   None
7          9     1     1    *8   None
8         13     9     5    *8  MVP-7
9          7     4     4    *8     GG
10        10     5     0    *8     GG
11         3     4     3    *8  AS,GG
12         5     0     4  *8/9     GG
13         6     1     1     8     GG
14         6     1     1   8/9   None
15         0     0     1   897   None
16         0     4     0  79/8   None
17         0     1     0  9/78   None
18         0     3     0  79/8   None
19         0     1     0  /798   None
20         0     0     0    /9   None

[21 rows x 29 columns]>

In [3]:
frame

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,28
0,18,CHW-min,D,92,318,318,87,9,4,4,...,None,None,None,None,None,None,None,None,None,None
1,19,CHW-min,A,128,473,473,148,23,4,14,...,None,None,None,None,None,None,None,None,None,None
2,Did not play in major or minor leagues (Milita...,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,Did not play in major or minor leagues (Milita...,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
4,22,CHW-min,"AA,A",105,337,337,95,14,4,6,...,None,None,None,None,None,None,None,None,None,None
5,23,CHW-min,AAA,37,140,118,21,29,1,4,...,47,3,1,1,0,INA · AA,None,None,None,None
6,23,CHW,AL,96,324,274,38,58,11,3,...,.625,72,81,3,3,2,0,2,987,None
7,24,CHW,AL,142,593,523,72,145,23,7,...,.785,116,227,9,8,9,1,1,*8,None
8,25,CHW,AL,149,623,515,78,140,26,7,...,.749,108,195,5,8,13,9,5,*8,MVP-7
9,26,CHW,AL,148,593,494,89,125,25,6,...,.753,105,192,7,9,7,4,4,*8,GG
10,27,CHW,AL,140,618,534,87,151,18,8,...,.832,123,251,10,4,10,5,0,*8,GG
11,28,CHW,AL,149,629,534,82,122,21,6,...,.711,92,200,10,9,3,4,3,*8,"AS,GG"
12,29,CHW,AL,133,454,396,56,89,6,6,...,.685,93,146,4,6,5,0,4,*8/9,GG
13,30,CHW,AL,106,347,298,30,62,8,4,...,.577,65,81,5,6,6,1,1,8,GG
14,31,KCA,AL,118,431,364,46,87,15,1,...,.656,89,113,10,3,6,1,1,8/9,None
15,32,CLE,AL,85,180,158,23,35,5,1,...,.639,85,51,2,2,0,0,1,897,None
16,33,TOT,MLB,80,231,198,24,47,11,1,...,.693,102,72,0,1,0,4,0,79/8,None
17,33,TOT,AL,30,64,55,5,11,0,0,...,.661,92,20,0,0,0,1,0,9/78,None
18,33,HOU,NL,50,167,143,19,36,11,1,...,.705,106,52,0,1,0,3,0,79/8,None
19,33,DET,AL,25,56,48,4,10,0,0,...,.637,86,16,0,0,0,1,0,/798,None
20,33,BOS,AL,5,8,7,1,1,0,0,...,.821,128,4,0,0,0,0,0,/9,None

In [23]:
table_head = table.find('thead')

p_head=[]
rows = table_head.find_all('tr')
for row in rows:
    cols = row.find_all('th')
    cols = [ele.text.strip() for ele in cols]
    p_head.append([ele for ele in cols if ele])

In [19]:
aph = np.array(p_head)

In [24]:
aph

array([<generator object <genexpr> at 0x000000000A5F8678>], dtype=object)

In [25]:
p_head

[['Year',
  'Age',
  'Tm',
  'Lg',
  'G',
  'PA',
  'AB',
  'R',
  'H',
  '2B',
  '3B',
  'HR',
  'RBI',
  'SB',
  'CS',
  'BB',
  'SO',
  'BA',
  'OBP',
  'SLG',
  'OPS',
  'OPS+',
  'TB',
  'GDP',
  'HBP',
  'SH',
  'SF',
  'IBB',
  'Pos',
  'Awards']]

In [6]:
import numpy as np

In [9]:
df = pd.DataFrame(index=p_head)

In [10]:
df

Empty DataFrame
Columns: []
Index: [Year, Age, Tm, Lg, G, PA, AB, R, H, 2B, 3B, HR, RBI, SB, CS, BB, SO, BA, OBP, SLG, OPS, OPS+, TB, GDP, HBP, SH, SF, IBB, Pos, Awards]